[package]
name = "kez"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.12"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
thiserror = "2.0.10"

[dev-dependencies]
tokio = { version = "1.43.0", features = ["full"] }
