use reqwest::RequestBuilder;

use crate::Transform;

/// Available heros in current dota2
/// # Example
/// ```rust,no_run
/// use kez::{dota2::{Hero, get_heroes::Heroes}, Client};
/// #[tokio::main]
/// async fn main() -> anyhow::Result<()> {
///   let client = Client::new("DUMMY_STEAM_API_KEY")?;
///   let heroes = client.get_heroes(()).await?;
///   let heroes: Vec<Hero> = heroes.heroes.iter().map(|hero| Hero::from(hero.id)).collect();
///   println!("{:?}", heroes);
///   Ok(())
/// }
/// ```
#[non_exhaustive]
#[repr(u8)]
#[derive(Clone, Copy, Debug)]
pub enum Hero {
    Unknown(u8) = 0,
    AntiMage = 1,
    Axe = 2,
    Bane = 3,
    Bloodseeker = 4,
    CrystalMaiden = 5,
    DrowRanger = 6,
    Earthshaker = 7,
    Juggernaut = 8,
    Mirana = 9,
    Morphling = 10,
    ShadowFiend = 11,
    PhantomLancer = 12,
    Puck = 13,
    Pudge = 14,
    Razor = 15,
    SandKing = 16,
    StormSpirit = 17,
    Sven = 18,
    Tiny = 19,
    VengefulSpirit = 20,
    Windranger = 21,
    Zeus = 22,
    Kunkka = 23,
    Lina = 25,
    Lion = 26,
    ShadowShaman = 27,
    Slardar = 28,
    Tidehunter = 29,
    WitchDoctor = 30,
    Lich = 31,
    Riki = 32,
    Enigma = 33,
    Tinker = 34,
    Sniper = 35,
    Necrophos = 36,
    Warlock = 37,
    Beastmaster = 38,
    QueenofPain = 39,
    Venomancer = 40,
    FacelessVoid = 41,
    WraithKing = 42,
    DeathProphet = 43,
    PhantomAssassin = 44,
    Pugna = 45,
    TemplarAssassin = 46,
    Viper = 47,
    Luna = 48,
    DragonKnight = 49,
    Dazzle = 50,
    Clockwerk = 51,
    Leshrac = 52,
    NaturesProphet = 53,
    Lifestealer = 54,
    DarkSeer = 55,
    Clinkz = 56,
    Omniknight = 57,
    Enchantress = 58,
    Huskar = 59,
    NightStalker = 60,
    Broodmother = 61,
    BountyHunter = 62,
    Weaver = 63,
    Jakiro = 64,
    Batrider = 65,
    Chen = 66,
    Spectre = 67,
    AncientApparition = 68,
    Doom = 69,
    Ursa = 70,
    SpiritBreaker = 71,
    Gyrocopter = 72,
    Alchemist = 73,
    Invoker = 74,
    Silencer = 75,
    OutworldDestroyer = 76,
    Lycan = 77,
    Brewmaster = 78,
    ShadowDemon = 79,
    LoneDruid = 80,
    ChaosKnight = 81,
    Meepo = 82,
    TreantProtector = 83,
    OgreMagi = 84,
    Undying = 85,
    Rubick = 86,
    Disruptor = 87,
    NyxAssassin = 88,
    NagaSiren = 89,
    KeeperoftheLight = 90,
    Io = 91,
    Visage = 92,
    Slark = 93,
    Medusa = 94,
    TrollWarlord = 95,
    CentaurWarrunner = 96,
    Magnus = 97,
    Timbersaw = 98,
    Bristleback = 99,
    Tusk = 100,
    SkywrathMage = 101,
    Abaddon = 102,
    ElderTitan = 103,
    LegionCommander = 104,
    Techies = 105,
    EmberSpirit = 106,
    EarthSpirit = 107,
    Underlord = 108,
    Terrorblade = 109,
    Phoenix = 110,
    Oracle = 111,
    WinterWyvern = 112,
    ArcWarden = 113,
    MonkeyKing = 114,
    DarkWillow = 119,
    Pangolier = 120,
    Grimstroke = 121,
    Hoodwink = 123,
    VoidSpirit = 126,
    Snapfire = 128,
    Mars = 129,
    Ringmaster = 131,
    Dawnbreaker = 135,
    Marci = 136,
    PrimalBeast = 137,
    Muerta = 138,
    Kez = 145,
}

impl Default for Hero {
    fn default() -> Self {
        Self::Unknown(0)
    }
}

impl From<u8> for Hero {
    fn from(value: u8) -> Self {
        match value {
            1 => Self::AntiMage,
            2 => Self::Axe,
            3 => Self::Bane,
            4 => Self::Bloodseeker,
            5 => Self::CrystalMaiden,
            6 => Self::DrowRanger,
            7 => Self::Earthshaker,
            8 => Self::Juggernaut,
            9 => Self::Mirana,
            10 => Self::Morphling,
            11 => Self::ShadowFiend,
            12 => Self::PhantomLancer,
            13 => Self::Puck,
            14 => Self::Pudge,
            15 => Self::Razor,
            16 => Self::SandKing,
            17 => Self::StormSpirit,
            18 => Self::Sven,
            19 => Self::Tiny,
            20 => Self::VengefulSpirit,
            21 => Self::Windranger,
            22 => Self::Zeus,
            23 => Self::Kunkka,
            25 => Self::Lina,
            26 => Self::Lion,
            27 => Self::ShadowShaman,
            28 => Self::Slardar,
            29 => Self::Tidehunter,
            30 => Self::WitchDoctor,
            31 => Self::Lich,
            32 => Self::Riki,
            33 => Self::Enigma,
            34 => Self::Tinker,
            35 => Self::Sniper,
            36 => Self::Necrophos,
            37 => Self::Warlock,
            38 => Self::Beastmaster,
            39 => Self::QueenofPain,
            40 => Self::Venomancer,
            41 => Self::FacelessVoid,
            42 => Self::WraithKing,
            43 => Self::DeathProphet,
            44 => Self::PhantomAssassin,
            45 => Self::Pugna,
            46 => Self::TemplarAssassin,
            47 => Self::Viper,
            48 => Self::Luna,
            49 => Self::DragonKnight,
            50 => Self::Dazzle,
            51 => Self::Clockwerk,
            52 => Self::Leshrac,
            53 => Self::NaturesProphet,
            54 => Self::Lifestealer,
            55 => Self::DarkSeer,
            56 => Self::Clinkz,
            57 => Self::Omniknight,
            58 => Self::Enchantress,
            59 => Self::Huskar,
            60 => Self::NightStalker,
            61 => Self::Broodmother,
            62 => Self::BountyHunter,
            63 => Self::Weaver,
            64 => Self::Jakiro,
            65 => Self::Batrider,
            66 => Self::Chen,
            67 => Self::Spectre,
            68 => Self::AncientApparition,
            69 => Self::Doom,
            70 => Self::Ursa,
            71 => Self::SpiritBreaker,
            72 => Self::Gyrocopter,
            73 => Self::Alchemist,
            74 => Self::Invoker,
            75 => Self::Silencer,
            76 => Self::OutworldDestroyer,
            77 => Self::Lycan,
            78 => Self::Brewmaster,
            79 => Self::ShadowDemon,
            80 => Self::LoneDruid,
            81 => Self::ChaosKnight,
            82 => Self::Meepo,
            83 => Self::TreantProtector,
            84 => Self::OgreMagi,
            85 => Self::Undying,
            86 => Self::Rubick,
            87 => Self::Disruptor,
            88 => Self::NyxAssassin,
            89 => Self::NagaSiren,
            90 => Self::KeeperoftheLight,
            91 => Self::Io,
            92 => Self::Visage,
            93 => Self::Slark,
            94 => Self::Medusa,
            95 => Self::TrollWarlord,
            96 => Self::CentaurWarrunner,
            97 => Self::Magnus,
            98 => Self::Timbersaw,
            99 => Self::Bristleback,
            100 => Self::Tusk,
            101 => Self::SkywrathMage,
            102 => Self::Abaddon,
            103 => Self::ElderTitan,
            104 => Self::LegionCommander,
            105 => Self::Techies,
            106 => Self::EmberSpirit,
            107 => Self::EarthSpirit,
            108 => Self::Underlord,
            109 => Self::Terrorblade,
            110 => Self::Phoenix,
            111 => Self::Oracle,
            112 => Self::WinterWyvern,
            113 => Self::ArcWarden,
            114 => Self::MonkeyKing,
            119 => Self::DarkWillow,
            120 => Self::Pangolier,
            121 => Self::Grimstroke,
            123 => Self::Hoodwink,
            126 => Self::VoidSpirit,
            128 => Self::Snapfire,
            129 => Self::Mars,
            131 => Self::Ringmaster,
            135 => Self::Dawnbreaker,
            136 => Self::Marci,
            137 => Self::PrimalBeast,
            138 => Self::Muerta,
            145 => Self::Kez,
            id => Self::Unknown(id),
        }
    }
}

impl From<Hero> for u8 {
    fn from(value: Hero) -> Self {
        match value {
            Hero::Unknown(id) => id,
            Hero::AntiMage => 1,
            Hero::Axe => 2,
            Hero::Bane => 3,
            Hero::Bloodseeker => 4,
            Hero::CrystalMaiden => 5,
            Hero::DrowRanger => 6,
            Hero::Earthshaker => 7,
            Hero::Juggernaut => 8,
            Hero::Mirana => 9,
            Hero::Morphling => 10,
            Hero::ShadowFiend => 11,
            Hero::PhantomLancer => 12,
            Hero::Puck => 13,
            Hero::Pudge => 14,
            Hero::Razor => 15,
            Hero::SandKing => 16,
            Hero::StormSpirit => 17,
            Hero::Sven => 18,
            Hero::Tiny => 19,
            Hero::VengefulSpirit => 20,
            Hero::Windranger => 21,
            Hero::Zeus => 22,
            Hero::Kunkka => 23,
            Hero::Lina => 25,
            Hero::Lion => 26,
            Hero::ShadowShaman => 27,
            Hero::Slardar => 28,
            Hero::Tidehunter => 29,
            Hero::WitchDoctor => 30,
            Hero::Lich => 31,
            Hero::Riki => 32,
            Hero::Enigma => 33,
            Hero::Tinker => 34,
            Hero::Sniper => 35,
            Hero::Necrophos => 36,
            Hero::Warlock => 37,
            Hero::Beastmaster => 38,
            Hero::QueenofPain => 39,
            Hero::Venomancer => 40,
            Hero::FacelessVoid => 41,
            Hero::WraithKing => 42,
            Hero::DeathProphet => 43,
            Hero::PhantomAssassin => 44,
            Hero::Pugna => 45,
            Hero::TemplarAssassin => 46,
            Hero::Viper => 47,
            Hero::Luna => 48,
            Hero::DragonKnight => 49,
            Hero::Dazzle => 50,
            Hero::Clockwerk => 51,
            Hero::Leshrac => 52,
            Hero::NaturesProphet => 53,
            Hero::Lifestealer => 54,
            Hero::DarkSeer => 55,
            Hero::Clinkz => 56,
            Hero::Omniknight => 57,
            Hero::Enchantress => 58,
            Hero::Huskar => 59,
            Hero::NightStalker => 60,
            Hero::Broodmother => 61,
            Hero::BountyHunter => 62,
            Hero::Weaver => 63,
            Hero::Jakiro => 64,
            Hero::Batrider => 65,
            Hero::Chen => 66,
            Hero::Spectre => 67,
            Hero::AncientApparition => 68,
            Hero::Doom => 69,
            Hero::Ursa => 70,
            Hero::SpiritBreaker => 71,
            Hero::Gyrocopter => 72,
            Hero::Alchemist => 73,
            Hero::Invoker => 74,
            Hero::Silencer => 75,
            Hero::OutworldDestroyer => 76,
            Hero::Lycan => 77,
            Hero::Brewmaster => 78,
            Hero::ShadowDemon => 79,
            Hero::LoneDruid => 80,
            Hero::ChaosKnight => 81,
            Hero::Meepo => 82,
            Hero::TreantProtector => 83,
            Hero::OgreMagi => 84,
            Hero::Undying => 85,
            Hero::Rubick => 86,
            Hero::Disruptor => 87,
            Hero::NyxAssassin => 88,
            Hero::NagaSiren => 89,
            Hero::KeeperoftheLight => 90,
            Hero::Io => 91,
            Hero::Visage => 92,
            Hero::Slark => 93,
            Hero::Medusa => 94,
            Hero::TrollWarlord => 95,
            Hero::CentaurWarrunner => 96,
            Hero::Magnus => 97,
            Hero::Timbersaw => 98,
            Hero::Bristleback => 99,
            Hero::Tusk => 100,
            Hero::SkywrathMage => 101,
            Hero::Abaddon => 102,
            Hero::ElderTitan => 103,
            Hero::LegionCommander => 104,
            Hero::Techies => 105,
            Hero::EmberSpirit => 106,
            Hero::EarthSpirit => 107,
            Hero::Underlord => 108,
            Hero::Terrorblade => 109,
            Hero::Phoenix => 110,
            Hero::Oracle => 111,
            Hero::WinterWyvern => 112,
            Hero::ArcWarden => 113,
            Hero::MonkeyKing => 114,
            Hero::DarkWillow => 119,
            Hero::Pangolier => 120,
            Hero::Grimstroke => 121,
            Hero::Hoodwink => 123,
            Hero::VoidSpirit => 126,
            Hero::Snapfire => 128,
            Hero::Mars => 129,
            Hero::Ringmaster => 131,
            Hero::Dawnbreaker => 135,
            Hero::Marci => 136,
            Hero::PrimalBeast => 137,
            Hero::Muerta => 138,
            Hero::Kez => 145,
        }
    }
}

impl Transform<Hero> for RequestBuilder {
    fn transform(self, value: Hero) -> Self {
        self.query(&[("hero_id", u8::from(value))])
    }
}
